<template>
  <b-jumbotron fluid class="mb-0 main-bg pt-100">
      <h3 class="text-center my-4">About Us</h3>
      <!-- <p class="small text-center">Release time：2018-12-10 15:49:57</p> -->
      <hr class="text-line mb-4">
      <p style="color: #666666;"><p style="margin-top:6px;margin-bottom:6px;line-height:150%"><span style="font-family: 仿宋_GB2312;line-height: 150%;font-size: 19px">Zhejiang Ebang Communication Co., Ltd., established in January 2010, is a national high-tech enterprise integrating R&D, production, sales and service. Data communication equipments  and blockchain computing devices are the leading products. The company specializes in data communication and chip design. The main business is divided into two categories:</span></p><p style="margin-top:6px;margin-bottom:6px;line-height:150%"><span style="font-family: 仿宋_GB2312;line-height: 150%;font-size: 19px">1. Telecommunication services: data communication equipment and optical fiber transmission equipment. The main customers are China Mobile, China Telecom and China Unicom.</span></p><p style="margin-top:6px;margin-bottom:6px;line-height:150%"><span style="font-family: 仿宋_GB2312;line-height: 150%;font-size: 19px">2. The blockchain business: the industrial chain based on integrated circuit design and independent research and development of chips, providing top blockchain computing equipment.</span></p><p style="margin-top:6px;margin-bottom:6px;line-height:150%"><span style="font-family: 仿宋_GB2312;line-height: 150%;font-size: 19px">In recent years, the company has won national level high-tech enterprises, national innovation funds, provincial high-tech enterprise research and development centers, Zhejiang science and technology small and medium-sized enterprises, and has three levels of computer information system integration qualification. Based on years of experience and accumulation in the communications industry, the company has a strong integrated circuit ASIC chip design capability, with R&D centers in Hangzhou, Shanghai, Wuhan and Suzhou. It has a research and development team of more than 140 people. The core members have more than ten years of hardware and software R & D strength. At the same time, the company cooperates with Samsung and TSMC and has the world&#39;s top and stable suppliers.</span></p><p style="margin-top:6px;margin-bottom:6px;line-height:150%"><span style="font-family: 仿宋_GB2312;line-height: 150%;font-size: 19px">In the future, the company will continue to develop and provide top BPUs, and develop blockchain applications, artificial intelligence data processors, blockchain applications and solutions for non-cryptocurrency, and 5G technologies.</span></p><p><br/></p>

      <p style="color: #666666;"><p><span style="font-size: 20px;"><strong style="font-size: 18px;">Contact Information:</strong></span></p><p><span style="font-size: 18px;"><strong><span style="font-family: arial, helvetica, sans-serif;">Zhejiang Ebang Communication Co., Ltd</span></strong><br/></span></p><p><span style="font-size: 18px;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Add: </span><span style="font-size: 18px; font-family: arial, helvetica, sans-serif;">26/F, 3/B, No. 66 Longchuanwu Road, Yuhang Economic and Technological Development Zone, Hangzhou</span></span></p><p><span style="font-family: arial, helvetica, sans-serif; font-size: 18px;">Sales Hotline: 86-571-88179077</span></p><p><span style="font-family: arial, helvetica, sans-serif; font-size: 18px;">After-sale Hotline：86-571-88179074</span></p><p><br/></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;"><strong>Ivy King </strong>(Sales)</span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Phone No.(WeChat):+86-17364526411<br/></span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Skype: live:ivy_1434  <br/></span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Email: ivy@ebang.com.cn</span></p><p><br/></p><p style="text-align: left;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;"></span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;"><strong>Lynn Xie </strong>(Sales)<br/></span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Phone No.(WeChat):+86-17764550235</span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Skype: lynnnesnay   <br/></span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Email: lynn@ebang.com.cn</span></p><p style="white-space: normal;"><br/></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;"><strong>Tammy Ni </strong>(Sales)<br/></span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Phone No.(WeChat):+86-19941242668</span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Skype: tammyni03   <br/></span></p><p style="white-space: normal;"><span style="font-family: arial, helvetica, sans-serif; font-size: 16px;">Email: tammy@ebang.com.cn</span></p><p style="text-align: left;"><br/></p><p style="text-align: left;"><br/></p>
    </b-jumbotron>
</template>

<style lang="scss" scoped>

</style>

